### ISSUE TITLE
Servlet Example

### ISSUE THREAD

**Issue by JoelProminic** [STARTcloud/hcl_roles#4]
@JustinProminic was asking about the servlet example from demo-tasks:
- Build script:  https://github.com/DominoVagrant/demo-v1.1/blob/main/dist-build/build-servlet-example.bsh
- Class:  https://github.com/DominoVagrant/demo-v1.1/blob/main/src/main/java/ExampleServlet.java

The goal for Ansible here is to setup a "project" where the user can build the servlet themselves.

From our discussion today, we would like to put these files in the home directory for java_user (/local/notesjava):

    ExampleServlet/
    ExampleServlet/ExampleServlet.java
    ExampleServlet/build-servlet-example.bsh

I updated the script like this, to work with the local directory:

```
#!/bin/bash

echo "Building servlet: ExampleServlet.java "

javac -verbose -source 1.8 -target 1.8 -classpath /opt/hcl/domino/notes/latest/linux/jvm/lib/ext/:/opt/hcl/domino/notes/latest/linux/ndext/jsdk.jar ExampleServlet.java

sudo mkdir -p /local/notesdata/domino/servlet

sudo cp ExampleServlet.class /local/notesdata/domino/servlet

sudo chown -R domino:domino /local/notesdata/domino/servlet
```

In order to run the servlet, you need to enable servlets in the server document (Internet Protocols > Domino Web Engine, change "Java servlet support" to "Domino Servlet Manager").  @JustinProminic didn't want to enable this for Domino servers by default, so we'll want to add instructions for the user in a comment or similar.  If we decide we want to add this to the server by default later, I think we need to set "HTTP_JavaServletSupport" to "1" (confirm this in Domino Designer).

The steps for the user will then be:
1. Vagrant SSH
2. `sudo su - java_user`
3. `cd ExampleServlet`
4. `./build-servlet-example.bsh`
5. Restart the Domino server or run `tell http restart`
6. Open the servlet at:  https://domino.%mydomain%/servlet/ExampleServlet

**Comment by MarkProminic** [comment]
That is what this role is for: https://github.com/STARTcloud/hcl_roles/tree/main/roles/domino_java_app_example

It contains the bits you bring up, but the tasks is just a skeleton. I will try to set this up.

**Comment by MarkProminic** [comment]
I have updated the role to:

1. Place the templated files into the specified directories as initially requested
2. Created a defaults/main.yml variable, ```build_example: true```  and if this is overridden by setting it to false ([Ansible Variable Precedence](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)), then it will not attempt to build the class file and place it into domino servlet directory. 
3. Allows the End user to make modifications to the build script and java example file on the server if they wish


I've done it this way so that people have a structure if they want to create various java examples and have them deployed via Ansible. I know its a bit more than you asked but it allows what you asked and sets people up for deploying/sharing their servlets.

I am marking this as closed, however if you wish to revisit this let me know
